In [ ]:
import numpy as np
from glob import glob
from tqdm import tqdm
import h5py
import nrrd
import nibabel as nib
import pandas as pd
import xlrd
import pdb
import SimpleITK as sitk
from skimage import transform, measure
import os
import pydicom
import matplotlib.pyplot as plt
%matplotlib inline

def load_scan(path):
    temp = [pydicom.dcmread(path + f) for f in os.listdir(path)]
    slices = [t for t in temp if t.Modality == 'CT']
    slices.sort(key = lambda x: int(x.InstanceNumber))
    try:
        slice_thickness = np.abs(slices[0].ImagePositionPatient[2] - slices[1].ImagePositionPatient[2])
    except:
        slice_thickness = np.abs(slices[0].SliceLocation - slices[1].SliceLocation)      
    for s in slices:
        s.SliceThickness = slice_thickness        
    return slices

def get_pixels_hu(scans):
    image = np.stack([s.pixel_array for s in scans]) 
    image = image.astype(np.float32)
    # Convert to Hounsfield units (HU)
    intercept = scans[0].RescaleIntercept
    slope = scans[0].RescaleSlope
    
    if slope != 1:
        image = slope * image.astype(np.float32)
        image = image.astype(np.float32)
        
    image += np.float32(intercept)
    
    return np.array(image, dtype=np.float32)

listt = glob('./Pancreas-CT/Pancreas-CT/*/*/Pancreas-*/')
base_dir = "./TCIA_pancreas_labels-02-05-2017/TCIA_pancreas_labels-02-05-2017/"

for item in tqdm(listt):
    name = str(item)
    name_id = name[35:39]
    patient_ct = load_scan(name)
    imgs_ct = get_pixels_hu(patient_ct)

    itk_img = sitk.ReadImage(base_dir +'label'+ name_id + '.nii.gz')
    origin = itk_img.GetOrigin()
    direction = itk_img.GetDirection()
    space = itk_img.GetSpacing()
    label = sitk.GetArrayFromImage(itk_img)
    

    image_gz = sitk.GetImageFromArray(imgs_ct)
    image_gz.SetOrigin(origin)
    image_gz.SetDirection(direction)
    image_gz.SetSpacing(space)
    sitk.WriteImage(image_gz, "./image"+name_id+".nii.gz")
#     plt.figure(figsize=(10, 10))
#     plt.title('CT Slice_10')
#     plt.imshow(imgs_ct[9],cmap='gray')
#     plt.axis('off')
#     plt.show()

In [ ]:
import numpy as np
from glob import glob
from tqdm import tqdm
import h5py
import nrrd
import nibabel as nib
import pandas as pd
import xlrd
import pdb
import SimpleITK as sitk
from skimage import transform, measure
import os
import pydicom
import matplotlib.pyplot as plt
%matplotlib inline
output_size =[96,96,96]
def ImageResample(sitk_image, new_spacing = [1,1,1], is_label = False):
    '''
    sitk_image:
    new_spacing: x,y,z
    is_label: if True, using Interpolator `sitk.sitkNearestNeighbor`
    '''
    size = np.array(sitk_image.GetSize())
    spacing = np.array(sitk_image.GetSpacing())
    new_spacing = np.array(new_spacing)
    new_size = size * spacing / new_spacing
    new_spacing_refine = size * spacing / new_size
    new_spacing_refine = [float(s) for s in new_spacing_refine]
    new_size = [int(s) for s in new_size]
    if not is_label:
        print(size)
        print(new_size)
        print(spacing)
        print(new_spacing_refine)
    resample = sitk.ResampleImageFilter()
    resample.SetOutputDirection(sitk_image.GetDirection())
    resample.SetOutputOrigin(sitk_image.GetOrigin())
    resample.SetSize(new_size)
    resample.SetOutputSpacing(new_spacing_refine)

    if is_label:
        resample.SetInterpolator(sitk.sitkNearestNeighbor)
    else:
        resample.SetInterpolator(sitk.sitkBSpline)
    newimage = resample.Execute(sitk_image)
    return newimage

def set_window_wl_ww(tensor):
    sl_window = [75,400]
    [wl,ww] = sl_window
    w_min, w_max = wl - ww//2, wl + ww//2
    tensor[tensor < w_min] = w_min
    tensor[tensor > w_max] = w_max
    tensor = (tensor - w_min) / (w_max - w_min)
    ### min max Normalization
    return tensor

def crop_roi(image, label):
    assert(image.shape == label.shape)
    print (image.shape)
    ### crop based on lung segmentation
    w, h, d = label.shape

    tempL = np.nonzero(label)
    minx, maxx = np.min(tempL[0]), np.max(tempL[0])
    miny, maxy = np.min(tempL[1]), np.max(tempL[1])

    px = max(output_size[0] - (maxx - minx), 0) // 2
    py = max(output_size[1] - (maxy - miny), 0) // 2
    minx = max(minx - px - 25, 0) #np.random.randint(5, 10)
    maxx = min(maxx + px + 25, w) #np.random.randint(5, 10)
    miny = max(miny - py - 25, 0)
    maxy = min(maxy + py + 25, h)
    
    image = image[minx:maxx, miny:maxy,:].astype(np.float32)
    label = label[minx:maxx, miny:maxy,:].astype(np.float32)
    return image, label

listt = glob('./Pancreas/image/*')

for item in tqdm(listt):
    name_image = str(item)
    name_label = name_image.replace('image', 'label')
#     pdb.set_trace
    itk_img = sitk.ReadImage(name_image)
#     origin =itk_img.GetOrigin()
#     direction = itk_img.GetDirection()
#     space = itk_img.GetSpacing()
    itk_img = ImageResample(itk_img)
    image = sitk.GetArrayFromImage(itk_img)
    image = np.transpose(image, (2,1,0))
    
    itk_label = sitk.ReadImage(name_label)
    itk_label = ImageResample(itk_label, is_label = True)
    label = sitk.GetArrayFromImage(itk_label)
    label = np.transpose(label, (2,1,0))

    assert(np.max(label) == 1 and np.min(label) == 0)
    assert(np.unique(label).shape[0] == 2)
    assert(np.shape(label)==np.shape(image))
    image = set_window_wl_ww(image)
#     print(image.shape)
#     plt.figure(figsize=(10, 10))
#     plt.title('CT Slice_enhanced_100')
#     plt.imshow(image[:,:,100],cmap='gray')
#     plt.show()
    image, label = crop_roi(image, label)
    image = (image - np.mean(image)) / np.std(image)
    print(image.shape)
    f = h5py.File(('./Pancreas_h5/image'+name_image[22:26] + '_norm.h5'), 'w')
    f.create_dataset('image', data=image, compression="gzip")
    f.create_dataset('label', data=label, compression="gzip")
    f.close()

  0%|                                                    | 0/82 [00:00<?, ?it/s]

[512 512 310]
[360, 360, 310]
[0.703125 0.703125 1.      ]
[1.0, 1.0, 1.0]
(360, 360, 310)
(168, 146, 310)


  1%|▌                                           | 1/82 [00:10<13:46, 10.20s/it]

[512 512 203]
[400, 400, 203]
[0.78200001 0.78200001 1.        ]
[1.0, 1.0, 1.0]
(400, 400, 203)
(164, 145, 203)


  2%|█                                           | 2/82 [00:17<11:09,  8.36s/it]

[512 512 206]
[460, 460, 206]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 206)
(168, 146, 206)


  4%|█▌                                          | 3/82 [00:24<10:37,  8.07s/it]

[512 512 210]
[460, 460, 210]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 210)
(170, 146, 210)


  5%|██▏                                         | 4/82 [00:32<10:22,  7.97s/it]

[512 512 221]
[460, 460, 221]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 221)
(212, 146, 221)


  6%|██▋                                         | 5/82 [00:41<10:31,  8.20s/it]

[512 512 226]
[480, 480, 226]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 226)
(210, 145, 226)


  7%|███▏                                        | 6/82 [00:50<10:49,  8.54s/it]

[512 512 201]
[420, 420, 201]
[0.8203125 0.8203125 1.       ]
[1.0, 1.0, 1.0]
(420, 420, 201)
(175, 145, 201)


  9%|███▊                                        | 7/82 [00:57<10:07,  8.10s/it]

[512 512 251]
[400, 400, 251]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 251)
(146, 145, 251)


 10%|████▎                                       | 8/82 [01:06<10:18,  8.36s/it]

[512 512 251]
[500, 500, 251]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 251)
(213, 145, 251)


 11%|████▊                                       | 9/82 [01:17<11:01,  9.06s/it]

[512 512 185]
[360, 360, 185]
[0.703125 0.703125 1.      ]
[1.0, 1.0, 1.0]
(360, 360, 185)
(179, 145, 185)


 12%|█████▏                                     | 10/82 [01:23<09:47,  8.16s/it]

[512 512 223]
[420, 420, 223]
[0.8203125 0.8203125 1.       ]
[1.0, 1.0, 1.0]
(420, 420, 223)
(174, 145, 223)


 13%|█████▊                                     | 11/82 [01:31<09:36,  8.12s/it]

[512 512 310]
[380, 380, 310]
[0.74218798 0.74218798 1.        ]
[1.0, 1.0, 1.0]
(380, 380, 310)
(182, 146, 310)


 15%|██████▎                                    | 12/82 [01:42<10:20,  8.87s/it]

[512 512 228]
[500, 500, 228]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 228)
(201, 145, 228)


 16%|██████▊                                    | 13/82 [01:51<10:17,  8.95s/it]

[512 512 221]
[462, 462, 221]
[0.90234375 0.90234375 1.        ]
[1.0, 1.0, 1.0]
(462, 462, 221)
(164, 146, 221)


 17%|███████▎                                   | 14/82 [01:59<09:58,  8.80s/it]

[512 512 221]
[500, 500, 221]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 221)
(151, 145, 221)


 18%|███████▊                                   | 15/82 [02:08<09:47,  8.77s/it]

[512 512 199]
[439, 439, 199]
[0.85799998 0.85799998 1.        ]
[1.0, 1.0, 1.0]
(439, 439, 199)
(211, 146, 199)


 20%|████████▍                                  | 16/82 [02:15<09:02,  8.22s/it]

[512 512 227]
[440, 440, 227]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 227)
(188, 146, 227)


 21%|████████▉                                  | 17/82 [02:23<09:00,  8.32s/it]

[512 512 187]
[380, 380, 187]
[0.7421875 0.7421875 1.       ]
[1.0, 1.0, 1.0]
(380, 380, 187)
(192, 145, 187)


 22%|█████████▍                                 | 18/82 [02:29<08:01,  7.53s/it]

[512 512 214]
[500, 500, 214]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 214)
(188, 157, 214)


 23%|█████████▉                                 | 19/82 [02:38<08:19,  7.92s/it]

[512 512 209]
[440, 440, 209]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 209)
(191, 146, 209)


 24%|██████████▍                                | 20/82 [02:46<08:11,  7.93s/it]

[512 512 206]
[475, 475, 206]
[0.92773438 0.92773438 1.        ]
[1.0, 1.0, 1.0]
(475, 475, 206)
(202, 146, 206)


 26%|███████████                                | 21/82 [02:54<08:10,  8.05s/it]

[512 512 216]
[500, 500, 216]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 216)
(177, 145, 216)


 27%|███████████▌                               | 22/82 [03:03<08:15,  8.26s/it]

[512 512 213]
[460, 460, 213]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 213)
(156, 145, 213)


 28%|████████████                               | 23/82 [03:11<08:03,  8.19s/it]

[512 512 222]
[460, 460, 222]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 222)
(163, 146, 222)


 29%|████████████▌                              | 24/82 [03:19<08:00,  8.29s/it]

[512 512 198]
[380, 380, 198]
[0.7421875 0.7421875 1.       ]
[1.0, 1.0, 1.0]
(380, 380, 198)
(194, 145, 198)


 30%|█████████████                              | 25/82 [03:26<07:27,  7.85s/it]

[512 512 211]
[481, 481, 211]
[0.93945312 0.93945312 1.        ]
[1.0, 1.0, 1.0]
(481, 481, 211)
(175, 159, 211)


 32%|█████████████▋                             | 26/82 [03:35<07:27,  8.00s/it]

[512 512 198]
[400, 400, 198]
[0.78200001 0.78200001 1.        ]
[1.0, 1.0, 1.0]
(400, 400, 198)
(171, 145, 198)


 33%|██████████████▏                            | 27/82 [03:42<07:02,  7.69s/it]

[512 512 205]
[400, 400, 205]
[0.78200001 0.78200001 1.        ]
[1.0, 1.0, 1.0]
(400, 400, 205)
(198, 145, 205)


 34%|██████████████▋                            | 28/82 [03:49<06:49,  7.59s/it]

[512 512 201]
[460, 460, 201]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 201)
(201, 145, 201)


 35%|███████████████▏                           | 29/82 [03:57<06:47,  7.70s/it]

[512 512 199]
[400, 400, 199]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 199)
(160, 145, 199)


 37%|███████████████▋                           | 30/82 [04:04<06:31,  7.53s/it]

[512 512 310]
[400, 400, 310]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 310)
(210, 145, 310)


 38%|████████████████▎                          | 31/82 [04:15<07:22,  8.67s/it]

[512 512 218]
[440, 440, 218]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 218)
(183, 146, 218)


 39%|████████████████▊                          | 32/82 [04:24<07:09,  8.59s/it]

[512 512 310]
[400, 400, 310]
[0.78125    0.78125    1.00000012]
[1.0, 1.0, 1.0]
(400, 400, 310)
(179, 145, 310)


 40%|█████████████████▎                         | 33/82 [04:35<07:38,  9.35s/it]

[512 512 466]
[485, 485, 233]
[0.94726562 0.94726562 0.5       ]
[1.0, 1.0, 1.0]
(485, 485, 233)
(204, 146, 233)


 41%|█████████████████▊                         | 34/82 [04:51<09:10, 11.47s/it]

[512 512 310]
[400, 400, 310]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 310)
(178, 145, 310)


 43%|██████████████████▎                        | 35/82 [05:03<09:00, 11.51s/it]

[512 512 231]
[480, 480, 231]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 231)
(153, 146, 231)


 44%|██████████████████▉                        | 36/82 [05:12<08:21, 10.91s/it]

[512 512 216]
[340, 340, 216]
[0.6640625 0.6640625 1.       ]
[1.0, 1.0, 1.0]
(340, 340, 216)
(146, 146, 216)


 45%|███████████████████▍                       | 37/82 [05:20<07:20,  9.79s/it]

[512 512 310]
[350, 350, 310]
[0.68359375 0.68359375 1.        ]
[1.0, 1.0, 1.0]
(350, 350, 310)
(166, 145, 310)


 46%|███████████████████▉                       | 38/82 [05:30<07:15,  9.90s/it]

[512 512 240]
[440, 440, 240]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 240)
(188, 145, 240)


 48%|████████████████████▍                      | 39/82 [05:39<06:57,  9.71s/it]

[512 512 210]
[439, 439, 210]
[0.85799998 0.85799998 1.        ]
[1.0, 1.0, 1.0]
(439, 439, 210)
(181, 145, 210)


 49%|████████████████████▉                      | 40/82 [05:47<06:28,  9.26s/it]

[512 512 203]
[481, 481, 203]
[0.93945312 0.93945312 1.        ]
[1.0, 1.0, 1.0]
(481, 481, 203)
(190, 146, 203)


 50%|█████████████████████▌                     | 41/82 [05:56<06:09,  9.00s/it]

[512 512 237]
[480, 480, 237]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 237)
(224, 145, 237)


 51%|██████████████████████                     | 42/82 [06:06<06:17,  9.44s/it]

[512 512 195]
[460, 460, 195]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 195)
(225, 146, 195)


 52%|██████████████████████▌                    | 43/82 [06:14<05:54,  9.10s/it]

[512 512 223]
[490, 490, 223]
[0.95703125 0.95703125 1.        ]
[1.0, 1.0, 1.0]
(490, 490, 223)
(217, 146, 223)


 54%|███████████████████████                    | 44/82 [06:24<05:52,  9.28s/it]

[512 512 310]
[380, 380, 310]
[0.7421875  0.7421875  1.00000012]
[1.0, 1.0, 1.0]
(380, 380, 310)
(146, 151, 310)


 55%|███████████████████████▌                   | 45/82 [06:35<06:01,  9.77s/it]

[512 512 310]
[380, 380, 310]
[0.7421875 0.7421875 1.       ]
[1.0, 1.0, 1.0]
(380, 380, 310)
(155, 146, 310)


 56%|████████████████████████                   | 46/82 [06:46<06:00, 10.01s/it]

[512 512 181]
[500, 500, 181]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 181)
(169, 146, 181)


 57%|████████████████████████▋                  | 47/82 [06:53<05:23,  9.24s/it]

[512 512 186]
[380, 380, 186]
[0.7421875 0.7421875 1.       ]
[1.0, 1.0, 1.0]
(380, 380, 186)
(163, 146, 186)


 59%|█████████████████████████▏                 | 48/82 [07:00<04:46,  8.42s/it]

[512 512 223]
[480, 480, 223]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 223)
(175, 146, 223)


 60%|█████████████████████████▋                 | 49/82 [07:09<04:43,  8.60s/it]

[512 512 310]
[340, 340, 310]
[0.6640625 0.6640625 1.       ]
[1.0, 1.0, 1.0]
(340, 340, 310)
(183, 145, 310)


 61%|██████████████████████████▏                | 50/82 [07:19<04:50,  9.09s/it]

[512 512 205]
[419, 419, 205]
[0.81999999 0.81999999 1.        ]
[1.0, 1.0, 1.0]
(419, 419, 205)
(216, 145, 205)


 62%|██████████████████████████▋                | 51/82 [07:26<04:28,  8.67s/it]

[512 512 310]
[470, 470, 310]
[0.91796875 0.91796875 1.        ]
[1.0, 1.0, 1.0]
(470, 470, 310)
(205, 146, 310)


 63%|███████████████████████████▎               | 52/82 [07:39<04:55,  9.86s/it]

[512 512 201]
[480, 480, 201]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 201)
(199, 146, 201)


 65%|███████████████████████████▊               | 53/82 [07:48<04:35,  9.49s/it]

[512 512 209]
[500, 500, 209]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 209)
(145, 158, 209)


 66%|████████████████████████████▎              | 54/82 [07:56<04:19,  9.26s/it]

[512 512 247]
[400, 400, 247]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 247)
(192, 147, 247)


 67%|████████████████████████████▊              | 55/82 [08:06<04:11,  9.32s/it]

[512 512 310]
[400, 400, 310]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 310)
(178, 145, 310)


 68%|█████████████████████████████▎             | 56/82 [08:17<04:16,  9.86s/it]

[512 512 310]
[360, 360, 310]
[0.703125 0.703125 1.      ]
[1.0, 1.0, 1.0]
(360, 360, 310)
(175, 146, 310)


 70%|█████████████████████████████▉             | 57/82 [08:27<04:10, 10.01s/it]

[512 512 193]
[350, 350, 193]
[0.68359375 0.68359375 1.        ]
[1.0, 1.0, 1.0]
(350, 350, 193)
(166, 145, 193)


 71%|██████████████████████████████▍            | 58/82 [08:34<03:33,  8.88s/it]

[512 512 206]
[480, 480, 206]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 206)
(184, 146, 206)


 72%|██████████████████████████████▉            | 59/82 [08:42<03:20,  8.70s/it]

[512 512 223]
[480, 480, 223]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 223)
(216, 150, 223)


 73%|███████████████████████████████▍           | 60/82 [08:51<03:16,  8.93s/it]

[512 512 201]
[480, 480, 201]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 201)
(173, 146, 201)


 74%|███████████████████████████████▉           | 61/82 [09:00<03:03,  8.73s/it]

[512 512 194]
[456, 456, 194]
[0.890625 0.890625 1.      ]
[1.0, 1.0, 1.0]
(456, 456, 194)
(167, 146, 194)


 76%|████████████████████████████████▌          | 62/82 [09:07<02:47,  8.38s/it]

[512 512 218]
[439, 439, 218]
[0.85799998 0.85799998 1.        ]
[1.0, 1.0, 1.0]
(439, 439, 218)
(201, 145, 218)


 77%|█████████████████████████████████          | 63/82 [09:16<02:39,  8.39s/it]

[512 512 215]
[500, 500, 215]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 215)
(191, 146, 215)


 78%|█████████████████████████████████▌         | 64/82 [09:25<02:34,  8.58s/it]

[512 512 310]
[400, 400, 310]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 310)
(210, 145, 310)


 79%|██████████████████████████████████         | 65/82 [09:36<02:41,  9.48s/it]

[512 512 233]
[440, 440, 233]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 233)
(196, 145, 233)


 80%|██████████████████████████████████▌        | 66/82 [09:46<02:31,  9.48s/it]

[512 512 201]
[400, 400, 201]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 201)
(170, 145, 201)


 82%|███████████████████████████████████▏       | 67/82 [09:53<02:11,  8.76s/it]

[512 512 210]
[460, 460, 210]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 210)
(188, 146, 210)


 83%|███████████████████████████████████▋       | 68/82 [10:01<02:00,  8.58s/it]

[512 512 310]
[360, 360, 310]
[0.703125 0.703125 1.      ]
[1.0, 1.0, 1.0]
(360, 360, 310)
(183, 145, 310)


 84%|████████████████████████████████████▏      | 69/82 [10:12<02:00,  9.25s/it]

[512 512 205]
[420, 420, 205]
[0.8203125 0.8203125 1.       ]
[1.0, 1.0, 1.0]
(420, 420, 205)
(200, 145, 205)


 85%|████████████████████████████████████▋      | 70/82 [10:19<01:45,  8.79s/it]

[512 512 209]
[400, 400, 209]
[0.78125 0.78125 1.     ]
[1.0, 1.0, 1.0]
(400, 400, 209)
(184, 145, 209)


 87%|█████████████████████████████████████▏     | 71/82 [10:27<01:33,  8.46s/it]

[512 512 205]
[400, 400, 205]
[0.78200001 0.78200001 1.        ]
[1.0, 1.0, 1.0]
(400, 400, 205)
(188, 145, 205)


 88%|█████████████████████████████████████▊     | 72/82 [10:35<01:21,  8.15s/it]

[512 512 223]
[500, 500, 223]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 223)
(202, 146, 223)


 89%|██████████████████████████████████████▎    | 73/82 [10:44<01:17,  8.58s/it]

[512 512 216]
[480, 480, 216]
[0.9375 0.9375 1.    ]
[1.0, 1.0, 1.0]
(480, 480, 216)
(215, 146, 216)


 90%|██████████████████████████████████████▊    | 74/82 [10:53<01:09,  8.64s/it]

[512 512 224]
[460, 460, 224]
[0.8984375 0.8984375 1.       ]
[1.0, 1.0, 1.0]
(460, 460, 224)
(198, 146, 224)


 91%|███████████████████████████████████████▎   | 75/82 [11:02<01:00,  8.65s/it]

[512 512 310]
[400, 400, 216]
[0.78125    0.78125    0.69999999]
[1.0, 1.0, 1.0]
(400, 400, 216)
(176, 145, 216)


 93%|███████████████████████████████████████▊   | 76/82 [11:11<00:53,  8.90s/it]

[512 512 310]
[440, 440, 310]
[0.859375 0.859375 1.      ]
[1.0, 1.0, 1.0]
(440, 440, 310)
(192, 145, 310)


 94%|████████████████████████████████████████▍  | 77/82 [11:23<00:49,  9.90s/it]

[512 512 206]
[500, 500, 206]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 206)
(210, 145, 206)


 95%|████████████████████████████████████████▉  | 78/82 [11:32<00:37,  9.48s/it]

[512 512 233]
[500, 500, 233]
[0.9765625 0.9765625 1.       ]
[1.0, 1.0, 1.0]
(500, 500, 233)
(187, 146, 233)
